onerror resume
wave tags  F0
wave update off
wave zoom range 1835380 1899944
wave group {Pixel Stream In} -backgroundcolor #004466
wave add -group {Pixel Stream In} ImgRsz_tb.dut.Clk -tag F0 -radix hexadecimal
wave add -group {Pixel Stream In} ImgRsz_tb.dut.Reset -tag F0 -radix hexadecimal
wave add -group {Pixel Stream In} ImgRsz_tb.ImgWidth -tag F0 -radix decimal
wave add -group {Pixel Stream In} ImgRsz_tb.ImgHeight -tag F0 -radix decimal
wave add -group {Pixel Stream In} ImgRsz_tb.PxlData -tag F0 -radix hexadecimal
wave add -group {Pixel Stream In} ImgRsz_tb.PxlX -tag F0 -radix decimal
wave add -group {Pixel Stream In} ImgRsz_tb.PxlY -tag F0 -radix decimal
wave add -group {Pixel Stream In} ImgRsz_tb.PxlVld -tag F0 -radix hexadecimal
wave add -group {Pixel Stream In} ImgRsz_tb.PxlRdy -tag F0 -radix hexadecimal
wave insertion [expr [wave index insertpoint] + 1]
wave group {Resized Pixel Stream Out} -backgroundcolor #aa0000
wave add -group {Resized Pixel Stream Out} {ImgRsz_tb.RszPxlData[0]} -tag F0 -radix hexadecimal
wave add -group {Resized Pixel Stream Out} ImgRsz_tb.RszPxlX -tag F0 -radix hexadecimal
wave add -group {Resized Pixel Stream Out} ImgRsz_tb.RszPxlY -tag F0 -radix hexadecimal
wave add -group {Resized Pixel Stream Out} ImgRsz_tb.RszPxlVld -tag F0 -radix hexadecimal
wave add -group {Resized Pixel Stream Out} ImgRsz_tb.RszPxlRdy -tag F0 -radix hexadecimal
wave add -group {Resized Pixel Stream Out} ImgRsz_tb.dut.Bbf.BlkIsExec -tag F0 -radix hexadecimal -subitemconfig { {ImgRsz_tb.dut.Bbf.BlkIsExec[7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[6]} {-radix hexadecimal -select} {ImgRsz_tb.dut.Bbf.BlkIsExec[5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0]} {-expand -radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsExec[0][0]} {-radix hexadecimal} }
wave insertion [expr [wave index insertpoint] + 1]
wave add ImgRsz_tb.dut.Igc.CapEntImg -tag F0 -radix hexadecimal
wave add {ImgRsz_tb.dut.Bbf.FcBlkBuf[0]} -tag F0 -radix hexadecimal -expand -subitemconfig { {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0]} {-expand -radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.FcBlkBuf[0][0][0]} {-radix hexadecimal} }
wave group Temp -backgroundcolor #004466
wave group Temp:Bwd -backgroundcolor #006666
wave add -group Temp:Bwd ImgRsz_tb.dut.Bbf.PxlVld_d1 -tag F0 -radix hexadecimal
wave add -group Temp:Bwd ImgRsz_tb.dut.Igc.PxlX_d1 -tag F0 -radix hexadecimal
wave add -group Temp:Bwd ImgRsz_tb.dut.Igc.PxlX_d1 -tag F0 -radix hexadecimal
wave insertion [expr [wave index insertpoint] + 1]
wave group Temp:Mid -backgroundcolor #550000
wave add -group Temp:Mid {ImgRsz_tb.dut.Ceg.CompBlkData[0]} -tag F0 -radix hexadecimal -subitemconfig { {ImgRsz_tb.dut.Ceg.CompBlkData[0][21]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][20]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][19]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][18]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][17]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][16]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][15]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][14]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][13]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][12]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][11]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][10]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][9]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][8]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkData[0][0]} {-radix hexadecimal} }
wave add -group Temp:Mid ImgRsz_tb.dut.Ceg.CompBlkXMsk -tag F0 -radix hexadecimal -subitemconfig { {ImgRsz_tb.dut.Ceg.CompBlkXMsk[7]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[6]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[5]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[4]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[3]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[2]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[1]} {-radix hexadecimal} {ImgRsz_tb.dut.Ceg.CompBlkXMsk[0]} {-radix hexadecimal} }
wave add -group Temp:Mid ImgRsz_tb.dut.Ceg.CompBlkYMsk -tag F0 -radix hexadecimal
wave add -group Temp:Mid ImgRsz_tb.dut.Bcs.BlkIsEnough -tag F0 -radix hexadecimal -subitemconfig { {ImgRsz_tb.dut.Bcs.BlkIsEnough[7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0]} {-expand -radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bcs.BlkIsEnough[0][0]} {-radix hexadecimal} }
wave add -group Temp:Mid ImgRsz_tb.dut.Ceg.CompBlkVld -tag F0 -radix hexadecimal
wave add -group Temp:Mid ImgRsz_tb.dut.Ceg.CompBlkRdy -tag F0 -radix hexadecimal
wave add -group Temp:Mid ImgRsz_tb.dut.Bbf.IntPxlCnt -tag F0 -radix decimal -expand -subitemconfig { {ImgRsz_tb.dut.Bbf.IntPxlCnt[7]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[6]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[5]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[4]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[3]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[2]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[1]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0]} {-expand -radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][7]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][6]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][5]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][4]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][3]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][2]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][1]} {-radix decimal -select} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][0]} {-radix decimal -select} } -select
wave insertion [expr [wave index insertpoint] + 1]
wave group Temp:Fwd -backgroundcolor #226600
wave add -group Temp:Fwd {ImgRsz_tb.dut.Bbf.CeRszPxlData[0]} -tag F0 -radix hexadecimal
wave add -group Temp:Fwd ImgRsz_tb.dut.Bbf.CeRszPxlXMsk -tag F0 -radix hexadecimal
wave add -group Temp:Fwd ImgRsz_tb.dut.Bbf.CeRszPxlYMsk -tag F0 -radix hexadecimal
wave add -group Temp:Fwd ImgRsz_tb.dut.Bbf.CeCompVld -tag F0 -radix hexadecimal
wave insertion [expr [wave index insertpoint] + 1]
wave insertion [expr [wave index insertpoint] + 1]
wave add ImgRsz_tb.dut.Bbf.BlkIsEnough -tag F0 -radix hexadecimal -subitemconfig { {ImgRsz_tb.dut.Bbf.BlkIsEnough[7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0]} {-expand -radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][7]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][6]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][5]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][4]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][3]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][2]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][1]} {-radix hexadecimal} {ImgRsz_tb.dut.Bbf.BlkIsEnough[0][0]} {-radix hexadecimal} }
wave add ImgRsz_tb.dut.Bbf.IntPxlCnt -tag F0 -radix decimal -expand -subitemconfig { {ImgRsz_tb.dut.Bbf.IntPxlCnt[7]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[6]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[5]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[4]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[3]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[2]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[1]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0]} {-expand -radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][7]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][6]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][5]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][4]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][3]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][2]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][1]} {-radix decimal} {ImgRsz_tb.dut.Bbf.IntPxlCnt[0][0]} {-radix decimal} }
wave add ImgRsz_tb.dut.Bbf.BlkBaseAddrHor -tag F0 -radix decimal -expand -subitemconfig { {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[7]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[6]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[5]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[4]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[3]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[2]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[1]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkBaseAddrHor[0]} {-radix decimal} }
wave add ImgRsz_tb.dut.Ceg.ProcBlkSz -tag F0 -radix decimal
wave add ImgRsz_tb.dut.Bbf.BlkOffsetHor -tag F0 -radix decimal -expand -subitemconfig { {ImgRsz_tb.dut.Bbf.BlkOffsetHor[7]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[6]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[5]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[4]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[3]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[2]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[1]} {-radix decimal} {ImgRsz_tb.dut.Bbf.BlkOffsetHor[0]} {-radix decimal} }
wave update on
wave top 30
